### PR TITLE
Issue/1066

### PR DESCRIPTION
**Pull request by dancgray**
Also added missing itemAriaExternal to properties.schema

### CODE REVIEW

**Comment by hrajotia** [comment]
+1

**Comment by brian-learningpool** [comment]
Perhaps the ARIA labels should have been defined in `globals`?

**Comment by moloko** [comment]
I see what @brian-learningpool is saying here... all other such ARIA labels are defined in [course.json](https://github.com/adaptlearning/adapt_framework/blob/master/src/course/en/course.json#L96-L124) so this one probably should be too... can set this up as a separate task, close this PR and merge #38 instead?

**Comment by dancgray** [comment]
Closing, issue created for itemAriaExternal move to `globals`:
https://github.com/adaptlearning/adapt_framework/issues/1116

**Pull request closed without merging**
