### PR TITLE
New: Added contentObject specific resources (fixes #84)

### LINKED ISSUE #84: adapt-contrib-resources: add contentObject specific resources
### Subject of the issue
Currently resources are global, it would be nice to be able to add contentObject specific resources.

Please +1 if you agree that this would be a nice feature.

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes #84

### New
* Allow content object specific resources

### CODE REVIEW

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by eleanor-heath — APPROVED** [review]

**Review by kirsty-hames — COMMENTED** [review]
contentObject specific resources are dependant on having course level `_resourcesItems` set. Is it expected there will always be course level resources and contentObject resources are in addition?

**Comment by oliverfoster** [comment]
> contentObject specific resources are dependant on having course level `_resourcesItems` set. Is it expected there will always be course level resources and contentObject resources are in addition?

It's either that the course ones are global or that they are restricted to just the main menu level. I guess a flag could be added to switch between the two?

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by kirsty-hames — APPROVED** [review]
Thanks @oliverfoster.

It might be useful to add a class to the global items should we want to style these differently to distinguish global and page specific resources.

[Suggestion for line 43 in resources.hbs](https://github.com/adaptlearning/adapt-contrib-resources/blob/0020063db2561f972cfe2fa478e689cce099ba79/templates/resources.hbs#L43):
`<div class="resources__item drawer__item is-{{_type}}{{#if _isGlobal}} is-global{{/if}} js-resources-item" role="listitem">`

**Pull request merged**
