### PR TITLE
Accessibility fix. https://adaptlearning.atlassian.net/browse/ABU-867

### PR DESCRIPTION
**Pull request by chris-steele**

### CODE REVIEW

**Comment by moloko** [comment]
+1

**Comment by oliverfoster** [comment]
@chris-steele could you change all resource related references from:
```
{{_globals._accessibility._ariaLabels. 
```
to
```
{{_globals._extensions._resources
```

as with the menu, and plp.

**Comment by taylortom** [comment]
+1

**Comment by oliverfoster** [comment]
+1

**Comment by moloko** [comment]
+1

**Pull request merged**
