### PR TITLE
update to use 2 spaces for indentation

### PR DESCRIPTION
**Pull request by nilslp**
Resources converted to use 2 spaces for indentation.

Extra commits are because v5 has not been synced with master.

### CODE REVIEW

**Comment by oliverfoster** [comment]
should probably wait for [#60](https://github.com/adaptlearning/adapt-contrib-resources/pull/60)

**Comment by oliverfoster** [comment]
#60 can be merged into here now @nilslp

**Comment by nilslp** [comment]
Haven't been back to this in a while, @oliverfoster happy this can be merged in now?

**Comment by moloko** [comment]
I believe this has been superseded by #62

**Pull request closed without merging**
