### PR TITLE
add 'translatable' property

### PR DESCRIPTION
**Pull request by moloko**
prep for multi-language support

### CODE REVIEW

**Comment by tomgreenfield** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Comment by dancgray** [comment]
@moloko didn't notice this PR before creating https://github.com/adaptlearning/adapt-contrib-resources/pull/39. Shall I amend my PR to just include the missing itemAriaExternal attribute?

**Comment by brian-learningpool** [comment]
+1

**Pull request merged**
