### PR TITLE
Add resources item type to ARIA label

### PR DESCRIPTION
**Pull request by taylortom**
Fixes ABU-829

### CODE REVIEW

**Comment by moloko** [comment]
+1

**Comment by taylortom** [comment]
I'm not sure `_type` is the best way to specify this, as I don't think it's translated?

**Comment by moloko** [comment]
good point, maybe it would be better to add a new property for this? 'ariaLabel' or something?

**Comment by oliverfoster** [comment]
or parsing the url to the filename and adding that to the end? so you'd get "exampleTranscript.pdf" or something similar

**Comment by taylortom** [comment]
Have updated this to pull in the resources_filterButtons label, which I think makes more sense, and will be translated.

**Comment by moloko** [comment]
+1 good idea

**Comment by oliverfoster** [comment]
the helper is unnecessary, use :

**Comment by taylortom** [comment]
ah cool, was looking for something like that

**Comment by taylortom** [comment]
Opening a new PR.

**Pull request closed without merging**
