### PR TITLE
Fix: Empty resource items array was breaking drawer load and added resource e2e tests (Issue/111)

### PR DESCRIPTION
**Pull request by lemmyadams**
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)

[//]: # (Link the PR to the original issue)
Addresses #111 

Chore:
* Resources tests added (e2e)

Fixes:
* Empty resource items array was breaking drawer load

### CODE REVIEW

**Comment by cahirodoherty-learningpool** [comment]
Currently blocked by issue 3 of https://github.com/adaptlearning/adapt_framework/issues/3472

**Comment by oliverfoster** [comment]
Please sort out data loading. Think more about making these tests generic. i.e. all of the test should run on any course, not just on the vanilla data

**Comment by cahirodoherty-learningpool** [comment]
> Please sort out data loading. Think more about making these tests generic. i.e. all of the test should run on any course, not just on the vanilla data

Hi Oliver, I believe I have addressed this in a new PR into this branch: https://github.com/adaptlearning/adapt-contrib-resources/pull/113

Can you have a look an confirm if those are the changes you think are needed please

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Comment by cahirodoherty-learningpool** [comment]
@oliverfoster Here is the updated resources tests. I've merged them into the original PR for easier viewing

**Review by ethan-lp — APPROVED** [review]

**Review by eleanor-heath — APPROVED** [review]

**Comment by cahirodoherty-learningpool** [comment]
Currently blocked by https://github.com/adaptlearning/adapt-contrib-core/issues/496

**Comment by cahirodoherty-learningpool** [comment]
Hi @oliverfoster Thanks for helping me progress the Core PR to fix drawer on location change. These tests are now passing as expected.

Chalk one up for tests! Caught another (albeit minor) bug 🚀

**Comment by oliverfoster** [comment]
No worries @cahirodoherty-learningpool

**Review by oliverfoster — APPROVED** [review]

**Pull request merged**
